### ISSUE TITLE
TLS/SSL Issue

### ISSUE THREAD

**Issue by mickyjtwin** [avivasolutionsnl/sitecore-docker#15]
https://github.com/avivasolutionsnl/sitecore-docker/blob/97a342576d742a1ac8b470258a04002b95889d87/solr/DockerFile#L17

I had an issue running the script where the Invoke-WebREquest failed because it could not create a secure channel. By including:

`[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 `

above the call, it forced latest TLS, as Powershell by default uses 1.0

**Comment by joostmeijles** [comment]
Tested with the latest build, problem no longer occurs: closing issue.
