### ISSUE TITLE
Why is the intermediate image removed?

### ISSUE THREAD

**Issue by geoffreysmith** [avivasolutionsnl/sitecore-docker#150]
In the compose file for xp and xc there's a reference to the intermediate file, yet this is removed in the nuke build. So really after running nuke, then compose it won't work as the image isn't there. Am I missing something?

**Comment by joostmeijles** [comment]
The intermediate images are only used at build-time. The compose file you are referring to is only used for building. Please see the `examples` directory for the compose files to use.
