### ISSUE TITLE
Create variants for SXA and JSS on the base Sitecore image

### ISSUE THREAD

**Issue by mlouage** [avivasolutionsnl/sitecore-docker#28]
Create multiple docker files for Sitecore that add different functionality like SXA and JSS. This way developers can pull the correct image from the (private) repository with everything already installed

**Comment by mlouage** [comment]
Could you give some guidance on how to do this and the way you would like to see the different Dockerfiles?

**Comment by joostmeijles** [comment]
@mlouage I see two options:
1) add it to the current Dockerfile; we have it than by default, but you lose the "naked" version. We have a Commerce related ticket for it: https://github.com/avivasolutionsnl/sitecore-commerce-docker/issues/18
2) create separate Dockerfiles; you have the possibility of choosing the installs, but possibly a large number of various Dockerfiles (and thus images) that will exist.

At the moment I am in favor of option 1.
@mlouage @Jonne what is your opinion on this?

**Comment by mlouage** [comment]
@joostmeijles Thanks Joost for the update. I would prefer option 1. That way you can really pick what image you want, maybe a customer does not have or use SXA and JSS so why have an image where these are build in?

**Comment by Jonne** [comment]
Option 2 would also have my perference. Where do we keep the docker files though? We've created a separate repository for the commerce docker images, but I think it would be to granular to put these in their own repository. Maybe we should merge the repositories?

**Comment by mlouage** [comment]
I think they belong here, there could be next to the sitecore folder other folders like sitecore-9.0.2-sxa or sitecore-9.0.2-jss. Once those images are build they are pushed to a repository right? And developers who use the images can just pull the one they want using tags?

**Comment by joostmeijles** [comment]
> Once those images are build they are pushed to a repository right?
> And developers who use the images can just pull the one they want using tags?

Correct.

My concern is that we should not create a new Docker image for each (small) feature. Maybe SXA and JSS are large enough to have their own images.

For example, we could have:
- sitecore:9.0.2-base
- sitecore:9.0.2-sxa
- sitecore:9.0.2-jss
- sitecore:9.0.2
The last one without post-fix would be the full (base + sxa + jss) version.

> Maybe we should merge the repositories?

Yes, I think that if we decide to do this we will have to combine the Sitecore XP and Sitecore XC repositories to keep a better overview.

**Comment by joostmeijles** [comment]
Proposal:
- Merge the [sitecore-docker](https://github.com/avivasolutionsnl/sitecore-docker) and [sitecore-commerce-docker](https://github.com/avivasolutionsnl/sitecore-commerce-docker) repos
- Create a directory per profile e.g. `xp` and `xc`
  - (optionally) create subdirectories with feature variations
- Use a better buildsystem than `docker-compose` to define the build, e.g. [dobi](https://github.com/dnephin/dobi)
- Different versions, e.g. 9.0.2, are managed using git tags and branches (i.e. we do not want a growing list of versions as for the current [sitecore/docker-images](https://github.com/Sitecore/docker-images/tree/develop/sitecore) approach)

**Comment by joostmeijles** [comment]
After some assessment, I propose to use [nuke.build](http://nuke.build) with [Docker Addon]( https://github.com/nuke-build/docker) to build the various Docker images.

Using a build-system tool allows us to:
- script the complete build
- explicitly specify the dependencies between the images
