### ISSUE TITLE
Wrong permissions for the database files

### ISSUE THREAD

**Issue by Barsonax** [avivasolutionsnl/sitecore-docker#56]
The permissions are set wrongly on the database files that appear if you run the containers:
![image](https://user-images.githubusercontent.com/19387223/53815830-bc4cb780-3f62-11e9-88b2-316300068dcf.png)

After changing the owner to my account so I can see the security tab we can see a unknown account which was previously the owner:
![image](https://user-images.githubusercontent.com/19387223/53943482-7f490800-40bd-11e9-80c4-5c5278463d0e.png)

Because this unknown account is the owner we get permission errors in the build of `mercury.demo.web`

![image](https://user-images.githubusercontent.com/19387223/53815937-f0c07380-3f62-11e9-8e4a-2d842ea234cc.png)

Runnning nuke with admin rights will workaround this permission issue but it might be better if the permissions are set correctly on the files themselves.

**Comment by Barsonax** [comment]
Workaround:
```
takeown /R /F databases
icacls databases /t /c /GRANT 'Users:F'
icacls databases /t /c /GRANT 'Authenticated Users:F'
```

**Comment by joostmeijles** [comment]
Closing the issue as it is project specific and does not occur in the sitecore-docker build.
