### ISSUE TITLE
c:\license error during XpSitecoreMssqlJss install 

### ISSUE THREAD

**Issue by bencarlson** [avivasolutionsnl/sitecore-docker#95]
Ran the nuke script once, and made it to XpSitecoreMssqlJss, ran is a second time skipping the successful builds. I've manually run the base images, and they have the c:\license file with license.xml in them, everything seems fine. Just haven't been able to get past this over the past few days or working on it. Any help is appreciated. Here's info from my console, error towards the bottom: 

==============================================
Target                    Status      Duration
----------------------------------------------
BaseSitecore              Skipped         0:00
XpXconnect                Skipped         0:00
BaseSolrBuilder           Skipped         0:00
BaseOpenJdk               Skipped         0:00
XpSolr                    Skipped         0:00
XpSitecore                Skipped         0:00
XpMssql                   Skipped         0:00
XpSitecoreMssqlJss        Failed          3:31
XpJss                     NotRun          0:00
XpSolrSxa                 NotRun          0:00
XpSitecoreMssqlSxa        NotRun          0:00
XpSxa                     NotRun          0:00
XcXconnect                NotRun          0:00
XcSolr                    NotRun          0:00
XcSitecoreIntermediate    NotRun          0:00
XcMssqlIntermediate       NotRun          0:00
XcCommerce                NotRun          0:00
XcSitecoreMssql           NotRun          0:00
Xc                        NotRun          0:00
XcSitecoreMssqlJss        NotRun          0:00
XcJss                     NotRun          0:00
XcSolrSxa                 NotRun          0:00
XcSitecoreMssqlSxa        NotRun          0:00
XcSxa                     NotRun          0:00
All                       NotRun          0:00
----------------------------------------------
Total                                     3:31
==============================================

Build failed on 4/12/2019 1:14:01 PM.

PS C:\Users\Ben\docker\sitecore-docker>

Here's the error: 

WorkingDirectory  : C:\
LogPath           : C:\install-jss.190412.log
WhatIf            : False
Verbose           : SilentlyContinue
Configuration     : C:\jss\install-jss.json
Debug             : SilentlyContinue
WarningAction     : Continue
ErrorAction       : Stop
InformationAction : Continue

Importing Module => SitecoreUtilityTasks
[-------------------------- CheckPaths : EnsurePath --------------------------]
[CheckPaths]:[Create] /files-mount/Sitecore JavaScript Services Server for Sitecore 9.0 11.0.0 rev. 181031.zip
[CheckPaths]:[Create] C:\inetpub\wwwroot\sitecore\App_Data\packages

[------------------- InstallPSEPackage : InstallModule -----------------------]
Installing module:  Sitecore JavaScript Services Server for Sitecore 9.0 11.0.0 rev. 181031.zip
http://sitecore/SiteUtilityPages/InstallModules.aspx?modules=Sitecore JavaScript Services Server for Sitecore 9.0 11.0.0 rev. 181031.zip
Install-SitecoreConfiguration :

        Error reading the C:\license directory.

         body {font-family:"Verdana";font-weight:normal;font-size:
.7em;color:black;}
         p {font-family:"Verdana";font-weight:normal;color:black;margin-top:
-5px}
         b {font-family:"Verdana";font-weight:bold;color:black;margin-top:
-5px}
         H1 {
font-family:"Verdana";font-weight:normal;font-size:18pt;color:red }
         H2 {
font-family:"Verdana";font-weight:normal;font-size:14pt;color:maroon }
         pre {font-family:"Consolas","Lucida
Console",Monospace;font-size:11pt;margin:0;padding:0.5em;line-height:14pt}
         .marker {font-weight: bold; color: black;text-decoration: none;}
         .version {color: gray;}
         .error {margin-bottom: 10px;}
         .expandable { text-decoration:underline; font-weight:bold;

**Comment by joostmeijles** [comment]
@bencarlson looks like you are missing the `xp/license/license.xml`.

See https://github.com/avivasolutionsnl/sitecore-docker/blob/master/azure-build-image.yml for details on how/where we copy prerequisites.

**Comment by bencarlson** [comment]
Thanks @joostmeijles  - I'll take a look at that file, but I've put the license.xml file in examples/xp/license/ xp/license/ xp/ and about 27 other places to try getting this to work... ;) I have not yet reviewed the azure-build-image.yml file, as I'm doing a local build; but I will look at it here. Thank you!

**Comment by joostmeijles** [comment]
The `license.xml` files is only required in `xp/license` and `xc/license`.

The `example` directory is not used during a build, it serves as an example after you have build all images.

**Comment by bencarlson** [comment]
Thanks @joostmeijles I totally get that the license.xml files only need to be in the xp/license and xc/license directories - I just meant that's not working, and I've tried a bunch of other things to try to get past this issue. 

Maybe explaining how I'm running the build will help... I'm running this on my local laptop (Windows 10 Pro), using the command: 'c:\> nuke' and have also tried running 'c:\> nuke XcSxa' which gets the same error. I'm successfully building many of the containers as shown below, but it's breaking on the  XcSitecoreMssql image. Does this information help? 



==============================================
Target                    Status      Duration
----------------------------------------------
BaseSitecore              Executed        3:17
XpXconnect                Executed        0:50
BaseSolrBuilder           Executed        0:49
BaseOpenJdk               Executed        0:48
XpSolr                    Executed        1:20
XpSitecore                Executed        1:14
XpMssql                   Executed        1:01
XcXconnect                Executed        5:01
XcSolr                    Executed        3:33
XcSitecoreIntermediate    Executed        5:06
XcMssqlIntermediate       Executed        3:27
XcCommerce                Executed       33:48
XcSitecoreMssql           Failed          2:15
Xc                        NotRun          0:00
XcSolrSxa                 NotRun          0:00
XcSitecoreMssqlSxa        NotRun          0:00
XcSxa                     NotRun          0:00
----------------------------------------------
Total                                    62:34
==============================================

**Comment by joostmeijles** [comment]
Seems like you are having a permission issue. Try setting the permissions mentioned here:  https://github.com/avivasolutionsnl/sitecore-docker/issues/56#issuecomment-470452133 for the `license` directory/file.

**Comment by bencarlson** [comment]
The issue was, Windows flagged the license.xml files as being from a different machine, so it wouldn't allow  any user to use them until I marked them as safe. Ugh. Thank you for your patience with this issue, and I sincerely appreciate your help, @joostmeijles !!
